### ISSUE TITLE
在节目进行时没有成功运行，求解答

### ISSUE THREAD

**Issue by 874769222** [steveyg/AnswerHelper#14]
Traceback (most recent call last):
  File "D:\download\AnswerHelper-master (1)\AnswerHelper-master\main.py", line 10, in <module>
    result = problem_utils.get_result()
  File "D:\download\AnswerHelper-master (1)\AnswerHelper-master\problem_utils.py", line 59, in get_result
    return get_chongding_by_api()
  File "D:\download\AnswerHelper-master (1)\AnswerHelper-master\problem_utils.py", line 40, in get_chongding_by_api
    while(json.loads(req.text)['msg']  != u"鎴愬姛"):
  File "D:\Python\lib\json\__init__.py", line 310, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 346, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 364, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

**Comment by steveyg** [comment]
最近那个api失效了，得用ocr的方式

**Comment by 874769222** [comment]
好的，感谢！
