### ISSUE TITLE
KeyError: 'words_result'

### ISSUE THREAD

**Issue by YuefengTang** [steveyg/AnswerHelper#18]
请问一下运行时出现KeyError: 'words_result'是什么问题？如下
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    question, answers = problem_utils.get_result()
  File "D:\AnswerHelper-master\problem_utils.py", line 53, in get_result
    return get_by_scan()
  File "D:\AnswerHelper-master\problem_utils.py", line 15, in get_by_scan
    words = img_utils.spot()['words_result']
KeyError: 'words_result

**Comment by zhoongjie** [comment]
在Config.py 文件中查看，百度的API定义关键词 是不是多了个空格

**Comment by steveyg** [comment]
应该是ocr数据处理的问题

**Comment by Sunhandsome** [comment]
我也报这个错误，请问解决了么，怎么解决？

**Comment by libai01** [comment]
> 
> 
> 在Config.py 文件中查看，百度的API定义关键词 是不是多了个空格
请问这个文件在哪里呢？
