### ISSUE TITLE
没有导入？

### ISSUE THREAD

**Issue by xiongshiran** [steveyg/AnswerHelper#2]
C:\Users\Administrator\Desktop\AnswerHelper-master>python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import img_utils
  File "C:\Users\Administrator\Desktop\AnswerHelper-master\img_utils.py", line 9
, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot

**Comment by steveyg** [comment]
貌似没有这个依赖，试试sudo pip install matplotlib 或者 apt-get install python-matplotlib

**Comment by lorenzorut** [comment]
装个pycharm，缺啥补啥
