### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by zyaloon** [steveyg/AnswerHelper#24]
错误代码
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    select1 = solve_utils.find_max_index(words_count)
  File "D:\pyback\AnswerHelper-master\AnswerHelper-master\solve_utils.py", line 40, in find_max_index
    return counts.index(max(counts))
ValueError: max() arg is an empty sequence

**Comment by zyaloon** [comment]
题目都没办法识别出来
